/*-------------------------------------------------------------------------------
 * dsd_ncurses.c
 * A dsd ncurses terminal printer
 *
 * ASCII art generated by:
 * https://fsymbols.com/generators/carty/
 *
 * LWVMOBILE
 * 2022-02 DSD-FME Florida Man Edition
 *-----------------------------------------------------------------------------*/
 /*
  * Copyright (C) 2010 DSD Author
  * GPG Key ID: 0x3F1D7FD0 (74EF 430D F7F2 0A48 FCE6  F630 FAA2 635D 3F1D 7FD0)
  *
  * Permission to use, copy, modify, and/or distribute this software for any
  * purpose with or without fee is hereby granted, provided that the above
  * copyright notice and this permission notice appear in all copies.
  *
  * THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
  * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
  * AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
  * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
  * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
  * OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  * PERFORMANCE OF THIS SOFTWARE.
  */

#include "dsd.h"
#include "git_ver.h"
char versionstr[25];
char * FM_bannerN[9] = {
  "                                 CTRL + C twice to exit",
  " ██████╗  ██████╗██████╗     ███████╗███╗   ███╗███████╗",
  " ██╔══██╗██╔════╝██╔══██╗    ██╔════╝████╗ ████║██╔════╝",
  " ██║  ██║╚█████╗ ██║  ██║    █████╗  ██╔████╔██║█████╗  ",
  " ██║  ██║ ╚═══██╗██║  ██║    ██╔══╝  ██║╚██╔╝██║██╔══╝  ",
  " ██████╔╝██████╔╝██████╔╝    ██║     ██║ ╚═╝ ██║███████╗",
  " ╚═════╝ ╚═════╝ ╚═════╝     ╚═╝     ╚═╝     ╚═╝╚══════╝",
  "https://github.com/lwvmobile/dsd-fme/tree/pulseaudio    "
};

char * SyncTypes[20] = {
  "P25P1_SYNC",
  "INV_P25P1_SYNC",
  "X2TDMA_BS/MS_DATA_SYNC",
  "INV_X2TDMA_BS/MS_DATA_SYNC",
  "X2TDMA_BS/MS_VOICE_SYNC",
  "INV_X2TDMA_BS/MS_VOICE_SYNC",
  "DSTAR_SYNC",
  "INV_DSTAR_SYNC",
  "NXDN_BS_VOICE_SYNC",     //8
  "INV_NXDN_BS_VOICE_SYNC", //9
  "DMR_BS/MS_DATA_SYNC",
  "INV_DMR_BS/MS_DATA_SYNC",
  "DMR_BS/MS_VOICE_SYNC",
  "INV_DMR_BS/MS_VOICE_SYNC",
  "PROVOICE_SYNC",          //14
  "INV_PROVOICE_SYNC",      //15
  "NXDN_BS_DATA_SYNC",      //16
  "INV_NXDN_BS_DATA_SYNC",  //17
  "DSTAR_HD",
  "INV_DSTAR_HD"

};

time_t nowN;
char * getTimeN(void) //get pretty hh:mm:ss timestamp
{
  time_t t = time(NULL);

  char * curr;
  char * stamp = asctime(localtime( & t));

  curr = strtok(stamp, " ");
  curr = strtok(NULL, " ");
  curr = strtok(NULL, " ");
  curr = strtok(NULL, " ");

  return curr;
}

void ncursesOpen ()
{
  mbe_printVersion (versionstr);
  setlocale(LC_ALL, "");
  initscr(); //Initialize NCURSES screen window
  start_color();
  init_pair(1, COLOR_YELLOW, COLOR_BLACK);      //Yellow/Amber for frame sync/control channel, NV style
  init_pair(2, COLOR_RED, COLOR_BLACK);        //Red for Terminated Calls
  init_pair(3, COLOR_GREEN, COLOR_BLACK);     //Green for Active Calls
  init_pair(4, COLOR_CYAN, COLOR_BLACK);     //Cyan for Site Extra and Patches
  init_pair(5, COLOR_MAGENTA, COLOR_BLACK); //Magenta for no frame sync/signal
  noecho();
  cbreak();
}

void
ncursesPrinter (dsd_opts * opts, dsd_state * state)
{
  int level;
  level = (int) state->max / 164;
  erase();
  //disabling until wide support can be built for LM, etc. $(ncursesw5-config --cflags --libs)
  //printw ("%s \n", FM_bannerN[0]); //top line in white
  //attron(COLOR_PAIR(4));
  //for (short int i = 1; i < 7; i++) { //following lines in cyan
    //printw("%s \n", FM_bannerN[i]); }
  //attroff(COLOR_PAIR(4));
  printw ("%s \n", FM_bannerN[7]); //http link
  printw ("Digital Speech Decoder: Florida Man Edition\n");
  printw ("Github Build Version: %s \n", GIT_TAG);
  printw ("mbelib version %s\n", versionstr);
  printw ("Time: ");
  printw ("%s ", getTimeN());
  if (SyncTypes[state->lastsynctype] != NULL)
  {
    printw ("%s \n", SyncTypes[state->lastsynctype]);
    //printw("%s ", state->ftype); //moved to front, some ftype strings have spaces in front of them, and others dont
    /* Not sure if I'm going to use the error bars yet
    if (opts->errorbars == 1)
    {
      printw("-"); //AFAIK, errorbars==1 is the internal value for if a system has inverted signal types, not at all misleading
    }
    else
    {
      printw("+");
    }
    */
    if (1 == 1){ //figure out method that will tell me when is active and when not active, maybe carrier but this doesn't print anyways unless activity
      attron(COLOR_PAIR(3));
    }
    printw ("%s %s\n", state->ftype, state->fsubtype); //some ftype strings have extra spaces in them
    if (state->lasttg < 0) //triggers compiler warning: comparison between pointer and integer
    {
      //sprintf(state->ftype, )
      //state->lasttg = state->ftype; //warning: assignment to ‘int’ from ‘char *
      state->lasttg = 0;
    }
    printw ("TG [%7i] RID [%12i] \n", state->lasttg, state->lastsrc); //variables to fill with info from other system types too
    //printw ("TG [%s] \n", state->lasttg);
    //printw ("TDMA activity:  %s %s \n", state->slot0light, state->slot1light);
    printw("In Level: [%2i%%] ", level);
    printw ("Voice Error [%s] \n", state->err_str); //no idea if this shows anything outside of TDMA or P1 or what
    if (1 == 1){ //same as above
      attroff(COLOR_PAIR(3));
    }
  }

  /*
  if (state->lastsynctype == 8 ||state->lastsynctype == 9 ||state->lastsynctype == 16 ||state->lastsynctype == 17)
  {
    if (state->samplesPerSymbol == 20)
      {
        //sprintf (state->ftype, " NXDN48      ");
        if (opts->errorbars == 1)
          {
            //printFrameSync (opts, state, " -NXDN48   ", synctest_pos + 1, modulation);
            printw("NXDN48 ");
            printw("%s \n", SyncTypes[state->lastsynctype]);
            printw("%s ", state->ftype);
          }
      }
    else
      {
        //sprintf (state->ftype, " NXDN96      ");
        if (opts->errorbars == 1)
          {
            //printFrameSync (opts, state, " -NXDN96   ", synctest_pos + 1, modulation);
            printw("NXDN96 ");
            printw("%s ", SyncTypes[state->lastsynctype]);
            printw("%s ", state->ftype);
          }
      }
  }
  */

  printw("\n"); //line return
  //add other interesting info to put here

  refresh();

}

void ncursesClose ()
{
  erase();
  refresh();
  endwin();
}
